# def out_fun():
#     print("Outer function")
#     def in_fun():
#         print("Inner function")
#     in_fun()
# out_fun()
# print("End of program")

# def fun1():
#     a=10
#     print("From fun1 a",a)
#     def fun2():
#         b=20
#         print("From fun2 b",b)
#         print("From fun2 a",a)
#     fun2()
#     print("From fun1 a",a)
# fun1()
# print("End of program")


# def fun1():
#     a=10
#     print("From fun1 a",a)
#     def fun2():
#         a=100
#         b=20
#         print("From fun2 b",b)
#         print("From fun2 a",a)
#     fun2()
#     print("From fun1 a",a)
#     #print("From fun1 b",b)  # This will raise an error because b is not defined in this scope
# fun1()

